#!/bin/sh /etc/rc.common
# shellcheck disable=SC2034,SC2154

START=99
USE_PROCD=1

script=$(readlink "$initscript")
NAME="$(basename ${script:-$initscript})"
config_load "$NAME"

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/podkop-smartlink daemon
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn 3600 5 0
    procd_set_param limits nofile=1024
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "$NAME"
}

stop_service() {
    /usr/bin/podkop-smartlink stop >/dev/null 2>&1
}

reload_service() {
    stop_service
    start_service
}
